repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: kafka-dev
    namespace: dev
    chart: bitnami/kafka
    version: 23.0.1
    values:
      - replicaCount: 1
        image:
          tag: latest
        auth:
          listeners.client.client.protocol: PLAINTEXT
          listeners.client.interbroker.protocol: PLAINTEXT
          enabled: false
    installed: true
    createNamespace: true

  - name: kafka-prod
    namespace: prod
    chart: bitnami/kafka
    version: 23.0.1
    values:
      - replicaCount: 5
        image:
          tag: 3.5.2
        auth:
          clientProtocol: sasl_plaintext
          interBrokerProtocol: sasl_plaintext
    installed: true
    createNamespace: true
