---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: mysql-operator
      labels:
        app: mysql-operator
    spec:
      serviceAccountName: admin
      containers:
        - name: mysql-operator
          image: roflmaoinmysoul/mysql-operator:1.0.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      tolerations:
        - key: "homework"
          operator: "Equal"
          value: "true"
