---
apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority: ./ca.crt
      server: ${APISERVER}
    name: kubernetes
contexts:
  - context:
      cluster: kubernetes
      namespace: homework
      user: cd
    name: cd-context
current-context: cd-context
users:
  - name: cd
    user:
      token: ${TOKEN}
