---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  resources:
    requests:
      storage: 500m
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: storage.class
