---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.nginx.name }}
  namespace: {{ include "homework.namespace" . }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    {{- range $i, $port := .Values.app.ports }}
    - port: {{ $port }}
      targetPort: {{ $port }}
    {{ end -}}