---
{{- range .Values.serviceAccounts }}
{{- if .create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ include "homework.namespace" $ }}
  {{- with .annotations }}
  annotations: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
---
{{- range .Values.roles }}
{{- if .create }}
kind: RoleBinding
metadata:
  namespace: {{ include "homework.namespace" $ }}
  name: role.{{ .name }}.binding
subjects:
{{- range $i, $val := .accounts }}
  - kind: ServiceAccount
    name: {{ $val }}
    namespace: {{ include "homework.namespace" $ }}
{{- end }}
roleRef:
  kind: Role
  name: role.{{ .name }}
  {{- with .apiGroup }}
  apiGroup:
    {{- toYaml . | nindent 2 }}
  {{- end }} 
{{- end }} 
---
{{- if .create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{- include "homework.namespace" $ }}
  name: role.{{ .name }}
{{- with .rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
---
{{- range .Values.clusterRoles }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "cluster.role.{{ .name }}"
{{- with .rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}

---
{{- if .create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "cluster.role.{{ .name }}.binding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "cluster.role.{{ .name }}"
subjects:
{{- range $i, $val := .accounts }}
  - kind: ServiceAccount
    name: {{ $val }}
    namespace: {{ include "homework.namespace" . }}
{{- end }}
{{- end }}
{{- end }}